// Generated by APEBind. Do not edit directly.
import type {
  APEProcessResult,
  ProcessSession,
  RawOptions,
} from './_runtime.js';

export interface ClientOptions {
  environment?: Readonly<Record<string, string | undefined>>;
}

export function createClient(options?: ClientOptions): import('./_runtime.js').APEClient;


export interface VersionParameters {
}

export function version(
): Promise<unknown>;


export interface EvaluateParameters {
  expr: string;
  symbols?: string;
}

export function evaluate(
  parameters: EvaluateParameters,
): Promise<unknown>;


export interface SimplifyParameters {
  expr: string;
  symbols?: string;
}

export function simplify(
  parameters: SimplifyParameters,
): Promise<unknown>;


export interface ExpandParameters {
  expr: string;
  symbols?: string;
}

export function expand(
  parameters: ExpandParameters,
): Promise<unknown>;


export interface FactorParameters {
  expr: string;
  symbols?: string;
}

export function factor(
  parameters: FactorParameters,
): Promise<unknown>;


export interface ApartParameters {
  expr: string;
  symbols?: string;
}

export function apart(
  parameters: ApartParameters,
): Promise<unknown>;


export interface DiffParameters {
  expr: string;
  symbols?: string;
  order?: number;
}

export function diff(
  parameters: DiffParameters,
): Promise<unknown>;


export interface IntegrateParameters {
  expr: string;
  symbols?: string;
}

export function integrate(
  parameters: IntegrateParameters,
): Promise<unknown>;


export interface SolveParameters {
  expr: string;
  symbols?: string;
}

export function solve(
  parameters: SolveParameters,
): Promise<unknown>;


export interface LimitParameters {
  expr: string;
  symbols?: string;
  point?: string;
}

export function limit(
  parameters: LimitParameters,
): Promise<unknown>;


export interface SeriesParameters {
  expr: string;
  symbols?: string;
  point?: string;
  order?: number;
}

export function series(
  parameters: SeriesParameters,
): Promise<unknown>;


export interface SubsParameters {
  expr: string;
  value: string;
  symbols?: string;
}

export function subs(
  parameters: SubsParameters,
): Promise<unknown>;


export interface NumericParameters {
  expr: string;
  symbols?: string;
  digits?: number;
}

export function numeric(
  parameters: NumericParameters,
): Promise<unknown>;

export function raw(
  arguments_: readonly unknown[],
  options?: RawOptions,
): Promise<APEProcessResult | ProcessSession>;
