// Generated by APEBind. Do not edit directly.
import { fileURLToPath } from 'node:url';

import { APEClient } from './_runtime.js';

const OPERATIONS = {
  "version": {
    "command_path": [
      "version"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": "result",
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "version"
        ],
        "token": "version",
        "positionals": [],
        "options": []
      }
    ]
  },
  "evaluate": {
    "command_path": [
      "eval"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "eval"
        ],
        "token": "eval",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "simplify": {
    "command_path": [
      "simplify"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "simplify"
        ],
        "token": "simplify",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "expand": {
    "command_path": [
      "expand"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "expand"
        ],
        "token": "expand",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "factor": {
    "command_path": [
      "factor"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "factor"
        ],
        "token": "factor",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "apart": {
    "command_path": [
      "apart"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "apart"
        ],
        "token": "apart",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "diff": {
    "command_path": [
      "diff"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "diff"
        ],
        "token": "diff",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--order"
            ],
            "primary_flag": "--order",
            "api_name": "order",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "integrate": {
    "command_path": [
      "integrate"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "integrate"
        ],
        "token": "integrate",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "solve": {
    "command_path": [
      "solve"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "solve"
        ],
        "token": "solve",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "limit": {
    "command_path": [
      "limit"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "limit"
        ],
        "token": "limit",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--point"
            ],
            "primary_flag": "--point",
            "api_name": "point",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "series": {
    "command_path": [
      "series"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "series"
        ],
        "token": "series",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--point"
            ],
            "primary_flag": "--point",
            "api_name": "point",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--order"
            ],
            "primary_flag": "--order",
            "api_name": "order",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "subs": {
    "command_path": [
      "subs"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "subs"
        ],
        "token": "subs",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--value"
            ],
            "primary_flag": "--value",
            "api_name": "value",
            "boolean": false,
            "required": true,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "numeric": {
    "command_path": [
      "numeric"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "numeric"
        ],
        "token": "numeric",
        "positionals": [
          {
            "api_name": "expr",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--var"
            ],
            "primary_flag": "--var",
            "api_name": "symbols",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--digits"
            ],
            "primary_flag": "--digits",
            "api_name": "digits",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  }
};
const RUNTIME = {
  "env_unset": [
    "PYTHONHOME",
    "PYTHONPATH",
    "PYTHONSTARTUP"
  ]
};

export function createClient({ environment = {} } = {}) {
  return new APEClient(
    fileURLToPath(new URL('./bin/sympy.com', import.meta.url)),
    OPERATIONS,
    RUNTIME,
    environment,
  );
}

const CLIENT = createClient();

export async function version(parameters = {}) {
  return CLIENT.invoke('version', parameters);
}

export async function evaluate(parameters = {}) {
  return CLIENT.invoke('evaluate', parameters);
}

export async function simplify(parameters = {}) {
  return CLIENT.invoke('simplify', parameters);
}

export async function expand(parameters = {}) {
  return CLIENT.invoke('expand', parameters);
}

export async function factor(parameters = {}) {
  return CLIENT.invoke('factor', parameters);
}

export async function apart(parameters = {}) {
  return CLIENT.invoke('apart', parameters);
}

export async function diff(parameters = {}) {
  return CLIENT.invoke('diff', parameters);
}

export async function integrate(parameters = {}) {
  return CLIENT.invoke('integrate', parameters);
}

export async function solve(parameters = {}) {
  return CLIENT.invoke('solve', parameters);
}

export async function limit(parameters = {}) {
  return CLIENT.invoke('limit', parameters);
}

export async function series(parameters = {}) {
  return CLIENT.invoke('series', parameters);
}

export async function subs(parameters = {}) {
  return CLIENT.invoke('subs', parameters);
}

export async function numeric(parameters = {}) {
  return CLIENT.invoke('numeric', parameters);
}

export async function raw(arguments_, options = {}) {
  return CLIENT.raw(arguments_, options);
}
